feat: Adding service delegation support
dodevops/terraform-azure-network pull request #3
Opened 2022-12-13 19:20 UTC by timdeluxe

2022-12-15 14:00 UTC, dploeger commented
I *think*, this is a breaking change, because Terraform currently has no optional arguments, so each use has to specify an (empty) list.

2022-12-15 14:01 UTC, dploeger requested changes
If it's a breaking change, mark it in the commit message.

2022-12-15 14:12 UTC, ThomasMinor approved these changes

2022-12-16 13:55 UTC, dploeger approved these changes
Very good. Thanks. 🎁

2022-12-16 13:56 UTC, merged